const dataList = {
    "list1":{
        "name":'同事',
        "list":[
            {
                "name":'q',
                "sex":'男',
                "like":'打篮球'
            },
            {
                "name":'w',
                "sex":'男',
                "like":'打乒乓球'
            },
            {
                "name":'e',
                "sex":'男',
                "like":'踢足球'
            }
        ]
    },
    "list2":{
        "name":'亲戚',
        "list":[
            {
                "name":'a',
                "sex":'女',
                "like":'打篮球a'
            },
            {
                "name":'s',
                "sex":'男',
                "like":'打篮球s'
            },
            {
                "name":'d',
                "sex":'男',
                "like":'打篮球d'
            },
            {
                "name":'f',
                "sex":'男',
                "like":'打篮球f'
            }
        ]
    },
    "list3":{
        "name":'朋友',
        "list":[
            {
                "name":'z',
                "sex":'男',
                "like":'打篮球z'
            },
            {
                "name":'x',
                "sex":'男',
                "like":'打篮球x'
            },
            {
                "name":'c',
                "sex":'男',
                "like":'打篮球c'
            },
            {
                "name":'v',
                "sex":'男',
                "like":'打篮球v'
            },
            {
                "name":'b',
                "sex":'男',
                "like":'打篮球b'
            }
        ]
    }
}