const dataList = {
    "list1":{
        "name":'同事',
        "list":[
            {
                "name":'q1',
                "sex":'男',
                "like":'打篮球'
            },
            {
                "name":'w2',
                "sex":'女',
                "like":'打乒乓球'
            },
            {
                "name":'e3',
                "sex":'男',
                "like":'踢足球'
            }
        ]
    },
    "list2":{
        "name":'亲戚',
        "list":[
            {
                "name":'a1',
                "sex":'女',
                "like":'打篮球a'
            },
            {
                "name":'s2',
                "sex":'男',
                "like":'打篮球s'
            },
            {
                "name":'d3',
                "sex":'男',
                "like":'打篮球d'
            },
            {
                "name":'f4',
                "sex":'男',
                "like":'打篮球f'
            }
        ]
    },
    "list3":{
        "name":'朋友',
        "list":[
            {
                "name":'z1',
                "sex":'男',
                "like":'打篮球z'
            },
            {
                "name":'x2',
                "sex":'男',
                "like":'打篮球x'
            },
            {
                "name":'c3',
                "sex":'男',
                "like":'打篮球c'
            },
            {
                "name":'v4',
                "sex":'男',
                "like":'打篮球v'
            },
            {
                "name":'b5',
                "sex":'男',
                "like":'打篮球b'
            }
        ]
    }
}